# Generated by Django 4.2.17 on 2026-03-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_inventario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pozo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("x", models.FloatField(blank=True, null=True)),
                ("y", models.FloatField(blank=True, null=True)),
                ("elevation", models.FloatField(blank=True, null=True)),
                ("well_type", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PuntoInSAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("subsidence", models.FloatField()),
                ("location", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Litologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.FloatField()),
                ("material", models.CharField(max_length=255)),
                ("resistivity", models.FloatField(blank=True, null=True)),
                ("velocity", models.FloatField(blank=True, null=True)),
                ("uge_class", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pozo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capas",
                        to="core.pozo",
                    ),
                ),
            ],
        ),
    ]
